export enum ActionType {
  //
  FETCH_STUDENTS_LIST = "FETCH_STUDENTS_LIST",
  FETCH_STUDENTS_LIST_SUCCESS = "FETCH_STUDENTS_LIST_SUCCESS",
  FETCH_STUDENTS_LIST_ERROR = "FETCH_STUDENTS_LIST_ERROR",

  //
  GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS",
  GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS",
  GET_STUDENT_DETAILS_ERROR = "GET_STUDENT_DETAILS_ERROR",
}
