export enum ActionType {
  // GET THE ENTIRE STUDENTS LIST
  FETCH_STUDENTS_LIST = "FETCH_STUDENTS_LIST",
  FETCH_STUDENTS_LIST_SUCCESS = "FETCH_STUDENTS_LIST_SUCCESS",
  FETCH_STUDENTS_LIST_ERROR = "FETCH_STUDENTS_LIST_ERROR",

  // GET DATA FOR A PARTICULAR STUDENT
  GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS",
  GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS",
  GET_STUDENT_DETAILS_ERROR = "GET_STUDENT_DETAILS_ERROR",

  // ADD STUDENT TO STUDENTS RECORD
  ADD_STUDENT = "ADD_STUDENT",
  ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS",

  // UDPATE STUDENT DETAILS INTO STUDENTS RECORD
  UPDATE_STUDENT_DETAILS = "UPDATE_STUDENT_DETAILS",
  UPDATE_STUDENT_DETAILS_SUCCESS = "UPDATE_STUDENT_DETAILS_SUCCESS",

  // REMOVE STUDENT FROM STUDENTS RECORD
  REMOVE_STUDENT = "REMOVE_STUDENT",
  REMOVE_STUDENT_SUCCESS = "RESTUDENT_DATA_SUCCESS",
}
