export enum ActionType {
  // GET THE ENTIRE STUDENT LIST
  FETCH_STUDENTS_LIST = "FETCH_STUDENTS_LIST",
  FETCH_STUDENTS_LIST_SUCCESS = "FETCH_STUDENTS_LIST_SUCCESS",
  FETCH_STUDENTS_LIST_ERROR = "FETCH_STUDENTS_LIST_ERROR",

  // GET DATA FOR INDIVIDUAL STUDENT
  GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS",
  GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS",
  GET_STUDENT_DETAILS_ERROR = "GET_STUDENT_DETAILS_ERROR",

  // ADD DATA TO STUDENTS RECORD
  ADD_STUDENT_DATA = "ADD_STUDENT_DATA",
  ADD_STUDENT_DATA_SUCCESS = "ADD_STUDENT_DATA_SUCCESS",
  ADD_STUDENT_DATA_ERROR = "ADD_STUDENT_DATA_ERROR",

  // REMOVE DATA TO STUDENTS RECORD
  REMOVE_STUDENT_DATA = "REMOVE_STUDENT_DATA",
  REMOVE_STUDENT_DATA_SUCCESS = "REMOVE_STUDENT_DATA_SUCCESS",
  REMOVE_STUDENT_DATA_ERROR = "REMOVE_STUDENT_DATA_ERROR",
}
